package falcon.player;

public enum Exemption {
    TELEPORT,
    JOIN_RESPAWN,
    WORLD_CHANGE,
    CHUNK_LOAD_DESYNC,
    VEHICLE_TRANSITION,
    ELYTRA_TRANSITION,
    VELOCITY_KNOCKBACK,
    PISTON_SLIME_HONEY,
    BED_CRAWL_SWIM_RIPTIDE_TRIDENT,
    PLUGIN_MOVEMENT
}
